ALTER TABLE sales
    ADD COLUMN IF NOT EXISTS eds_required BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS eds_validated BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS eds_provider VARCHAR(50),
    ADD COLUMN IF NOT EXISTS prescription_number VARCHAR(100);
